site_name: SaLinA

theme:
  name: "material"

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - from unittest.mock import MagicMock as mock
            - sys.path.append("salina")
          selection:
            new_path_syntax: true
