logger:
  classname: salina.logger.TFLogger
  log_dir: ./finetune_cartpole
  every_n_seconds: 10
  modulo: 1
  verbose: False

scenario:
  classname: salina_cl.scenarios.brax.halfcheetah.halfcheetah_test
  n_train_envs: 32
  n_evaluation_envs: 32
  n_steps: 10000

model:
  classname: salina_cl.algorithms.td3_finetune.model.FineTune

  params:
    evaluation:
      device: cuda:0
      seed: 10
      n_rollouts: 10
      evaluate_success: False

    td3:
      seed: 11

      learning_device: cuda:0
      acquisition_device: cuda:0
      buffer_device: cuda:0

      optimizer_policy:
        classname: torch.optim.Adam
        lr: 0.0003

      optimizer_q:
        classname: torch.optim.Adam
        lr: 0.0003

      optimizer_alpha:
        classname: torch.optim.Adam
        lr: 0.0003

      clip_grad: 10.0
      n_processes: 1

      control_every_n_epochs: 10
      buffer_time_size: 2
      initial_buffer_size: 1
      buffer_size: 1000000
      n_timesteps: 16
      batch_size: 64
      inner_epochs: 64
      update_target_tau: 0.005
      action_noise: 0.2
      target_noise: 0.1
      noise_clip: 0.5
      discount_factor: 0.99
      reward_scaling: 1.0

      time_limit: 0

    td3_agent:
      classname: salina_cl.algorithms.td3_finetune.agents.ActionAgent
      hidden_size: 256
      n_layers: 2
      input_dimension: nil
      output_dimension: nil

    q_agent:
      classname: salina_cl.algorithms.td3_finetune.agents.QAgent
      hidden_size: 256
      n_layers: 2
      input_dimension: nil
      output_dimension: nil
