logger:
  classname: salina.logger.TFLogger
  log_dir: brax
  modulo: 10
  every_n_seconds: 10
  verbose: True

env_name: halfcheetah
env:
    classname: brax.envs.create_gym_env
    env_name: ${env_name}

q_agent:
  classname: salina_examples.rl.sac.agents.QMLPAgent
  hidden_size: 256
  n_layers: 2
  env: ${env}

action_agent:
  classname: salina_examples.rl.sac.agents.ActionMLPAgent
  hidden_size: 256
  n_layers: 2
  env: ${env}

algorithm:
  brax_env:
    env_name: ${env_name}
    episode_length: 1000

  env_seed: 432

  max_epoch: 10000000

  optimizer:
    classname: torch.optim.Adam
    lr: 0.001

  use_observation_normalizer: True
  alpha: 0.2
  learning_alpha: True
  policy_delay: 2
  clip_grad: 2
  inner_epochs: 2
  batch_size: 128
  discount_factor: 0.97
  update_target_tau: 0.005
  device: cpu

  n_envs: 128
  n_timesteps: 2
  overlapping_timesteps: 1
  buffer_time_size: 2
  buffer_size: 5000000
  initial_buffer_size: 10000
  reward_scaling: 10.0

  validation:
    evaluate_every: 100
    n_envs: 16
    env_seed: 32
