logger:
  classname: salina.logger.TFLogger
  log_dir: ./sac
  modulo: 10
  every_n_seconds: 10
  verbose: True

env:
  classname: salina_examples.rl.sac.agents.make_gym_env
  env_name: Pendulum-v1
  max_episode_steps: 100

q_agent:
  classname: salina_examples.rl.sac.agents.QMLPAgent
  hidden_size: 256
  n_layers: 2
  env: ${env}

action_agent:
  classname: salina_examples.rl.sac.agents.ActionMLPAgent
  hidden_size: 256
  n_layers: 2
  env: ${env}

algorithm:
  env: ${env}

  env_seed: 432

  max_epoch: 10000000

  optimizer:
    classname: torch.optim.Adam
    lr: 0.0003


  inner_epochs: 2
  policy_delay: 2
  batch_size: 128
  alpha: 0.0
  clip_grad: 2
  discount_factor: 0.99
  update_target_tau: 0.005
  loss_device: cpu
  reward_scaling: 0.1
  n_envs: 4
  n_processes: 4
  n_timesteps: 2
  overlapping_timesteps: 1
  buffer_time_size: 2
  buffer_size: 100000
  initial_buffer_size: 10000
