logger:
  classname: salina.logger.TFLogger
  log_dir: ./finetune_cartpole
  every_n_seconds: 10
  modulo: 1
  verbose: False

scenario:
  classname: salina_cl.scenarios.classic_control.cartpole.cartpole_test
  n_train_envs: 32
  n_evaluation_envs: 32
  n_steps: 100000
  n_tasks: 6

model:
  classname: salina_cl.algorithms.sac_finetune.model.FineTune

  params:
    evaluation:
      device: cpu
      seed: 10
      n_rollouts: 10
      evaluate_success: False

    sac:
      seed: 11

      learning_device: cpu
      acquisition_device: cpu
      buffer_device: cpu

      optimizer_policy:
        classname: torch.optim.Adam
        lr: 0.0003

      optimizer_q:
        classname: torch.optim.Adam
        lr: 0.0003

      optimizer_alpha:
        classname: torch.optim.Adam
        lr: 0.0003

      clip_grad: 10.0
      n_processes: 1

      control_every_n_epochs: 10
      buffer_time_size: 2
      initial_buffer_size: 1
      buffer_size: 1000000
      n_timesteps: 16
      batch_size: 64
      inner_epochs: 16
      update_target_tau: 0.005
      alpha: 0.1
      learning_alpha: False
      discount_factor: 0.95
      reward_scaling: 1.0

      time_limit: 0

    sac_agent:
      classname: salina_cl.algorithms.sac_finetune.agents.ActionAgent
      hidden_size: 256
      n_layers: 2
      input_dimension: nil
      output_dimension: nil

    q_agent:
      classname: salina_cl.algorithms.sac_finetune.agents.QAgent
      hidden_size: 256
      n_layers: 2
      input_dimension: nil
      output_dimension: nil
