name: ppo_finetune
seed: 0

defaults:
  - logger: logger
  - scenario: cartpole_7tasks
  - algorithm: ppo_cpu
  - override hydra/launcher: submitit_slurm

logger:
  classname: salina.logger.TFLogger
  log_dir: .
  every_n_seconds: 10
  modulo: 1
  verbose: False

model:
  classname: salina_cl.models.models.OneStep
  seed: ${seed}
  params:
    evaluation:
      device: cpu
      seed: ${seed}
      n_rollouts: 1
      evaluate_success: False

    algorithm: ${algorithm}

    policy_agent:
      classname: salina_cl.agents.single_agents.ActionAgent
      hidden_size: 8
      n_layers: 2
      input_dimension: nil
      output_dimension: nil

    critic_agent:
      classname: salina_cl.agents.single_agents.CriticAgent
      hidden_size: 32
      n_layers: 2
      input_dimension: nil

hydra:
  run:
    dir: results/run/${scenario.name}/${name}/${hydra.job.override_dirname}/seed=${seed}
  sweep:
    dir: resuls/multirun/${scenario.name}/${name}/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.num}
  job:
    config:
      override_dirname:
        item_sep: /
        exclude_keys:
          - seed
  launcher:
    mem_gb: 16
    max_num_timeout: 0
    cpus_per_task: 1
    signal_delay_s: 30
    timeout_min: 10
    gpus_per_node: 1
    tasks_per_node: 1
    partition: learnlab
  job_logging:
    root:
      handlers: []
