name: ppo_subspace
seed: 0

defaults: 
  - scenario: cartpole_7tasks
  - algorithm: ppo_cpu
  - override hydra/launcher: submitit_slurm

logger:
  classname: salina.logger.TFLogger
  log_dir: .
  every_n_seconds: 10
  modulo: 1
  verbose: False

model:
  classname: salina_cl.models.subspace.TwoSteps
  seed: ${seed}
  params:
    evaluation:
      device: cpu
      seed: ${seed}
      n_rollouts: 5
      evaluate_success: False

    algorithm1:
      classname: salina_cl.algorithms.k_shot.k_shot
      params:
        n_processes: 0
        acquisition_device: cpu
        budget: 0.6
        
    algorithm2: ${algorithm}
        
    policy_agent:
      classname: salina_cl.agents.subspace_agents.SubspaceActionAgent
      hidden_size: 8
      n_layers: 2
      input_dimension: nil
      output_dimension: nil
      n_initial_anchors: 1
      dist_type: flat

    critic_agent:
      classname: salina_cl.agents.subspace_agents.CriticAgent
      hidden_size: 32
      n_layers: 2
      input_dimension: nil
      n_anchors:

hydra:
  run:
    dir: results/run/${scenario.name}/${name}/${hydra.job.override_dirname}/seed=${seed}
  sweep:
    dir: resuls/multirun/${scenario.name}/${name}/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.num}
  job:
    config:
      override_dirname:
        item_sep: /
        exclude_keys:
          - seed
  launcher:
    mem_gb: 16
    max_num_timeout: 0
    cpus_per_task: 1
    signal_delay_s: 30
    timeout_min: 10
    gpus_per_node: 1
    tasks_per_node: 1
    partition: learnlab
  job_logging:
    root:
      handlers: []