name: ppo_fromscratch
seed: 0

defaults: 
  - scenario: halfcheetah_hard
  - algorithm: ppo
  - override hydra/launcher: submitit_slurm

logger:
  classname: salina.logger.TFLogger
  log_dir: .
  every_n_seconds: 10
  modulo: 1
  verbose: False

model:
  classname: salina_cl.models.models.Baseline
  seed: ${seed}
  params:
    evaluation:
      device: cuda:0
      seed: ${seed}
      n_rollouts: 1
      evaluate_success: False

    algorithm: ${algorithm}

    policy_agent:
      classname: salina_cl.agents.single_agents.ActionAgent
      hidden_size: 64
      n_layers: 4
      input_dimension: nil
      output_dimension: nil

    critic_agent:
      classname: salina_cl.agents.single_agents.CriticAgent
      hidden_size: 256
      n_layers: 4
      input_dimension: nil

hydra:
  run:
    dir: results/run/${scenario.name}/${name}/${hydra.job.override_dirname}/seed=${seed}
  sweep:
    dir: results/multirun/${scenario.name}/${name}/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.num}
  job:
    config:
      override_dirname:
        item_sep: /
        exclude_keys:
          - seed
    env_set:
      OMP_NUM_THREADS: '1'
      XLA_PYTHON_CLIENT_PREALLOCATE: 'false'
  launcher:
    mem_gb: 16
    max_num_timeout: 0
    cpus_per_task: 1
    signal_delay_s: 30
    timeout_min: 200
    gpus_per_node: 1
    tasks_per_node: 1
    partition: learnlab
    comment: CoLLa2022
  job_logging:
    root:
      handlers: []
