name: ppo_subspace
seed: 0

defaults: 
  - logger: logger
  - scenario: halfcheetah_hard
  - algorithm: ppo
  - override hydra/launcher: submitit_slurm

model:
  classname: salina_cl.models.subspace.TwoSteps
  seed: ${seed}
  params:
    evaluation:
      device: cuda:0
      seed: 10
      n_rollouts: 1
      evaluate_success: False

    algorithm1:
      classname: salina_cl.algorithms.k_shot.k_shot
      params:
        n_processes: 0
        acquisition_device: cuda:0
        k: 512
        n_envs: ${scenario.n_train_envs}
        budget: 0.15
        
    algorithm2: ${algorithm}

    policy_agent:
      classname: salina_cl.agents.subspace_agents.SubspaceActionAgent
      hidden_size: 64
      n_layers: 4
      input_dimension: nil
      output_dimension: nil

      n_initial_anchors: 1
      dist_type: flat

    critic_agent:
      classname: salina_cl.agents.subspace_agents.CriticAgent
      hidden_size: 256
      n_layers: 4
      input_dimension: nil
      n_anchors:

hydra:
  run:
    dir: results/run/${scenario.name}/${name}/${hydra.job.override_dirname}/seed=${seed}
  sweep:
    dir: results/multirun/${scenario.name}/${name}/${now:%Y-%m-%d_%H-%M-%S}/${hydra.job.override_dirname}/seed=${seed}
    subdir: ${hydra.job.num}
  job:
    env_set:
      OMP_NUM_THREADS: '1'
      XLA_PYTHON_CLIENT_PREALLOCATE: 'false'
    config:
      override_dirname:
        item_sep: /
        exclude_keys:
          - seed
  launcher:
    mem_gb: 16
    max_num_timeout: 0
    cpus_per_task: 1
    signal_delay_s: 30
    timeout_min: 300
    gpus_per_node: 1
    tasks_per_node: 1
    partition: learnlab
    comment: CoLLa2022
  job_logging:
    root:
      handlers: []