logger:
  classname: salina.logger.TFLogger
  log_dir: ./bc
  modulo: 1
  every_n_seconds: 10
  verbose: True

n_envs: 1
env_name: walker2d-medium-expert-v2
#env_name: antmaze-medium-diverse-v0
embedding_size: 64
env:
  classname: salina_examples.offline_rl.d4rl.make_d4rl_env
  env_name: ${env_name}
  max_episode_steps: 1000

agent:
  classname: salina_examples.offline_rl.decision_transformer.agents.transition_transformers
  encoder:
    env: ${env}
    n_layers: 1
    hidden_size: 256
    embedding_size: ${embedding_size}
    max_episode_steps: 1000
    use_timestep: False
    use_reward_to_go: False
  transformer:
    n_layers: 1
    n_heads: 1
    n_steps: 1
    use_layer_norm: False
  decoder:
    env: ${env}
    n_layers: 1
    hidden_size: 256

algorithm:
  env_seed: 432
  batch_size: 32
  max_epoch: 10000000
  clip_grad: 2
  optimizer:
    classname: torch.optim.Adam
    lr: 0.001
  reward_scale: 1000.0
  target_rewards:
    - 4000
    - 3600
    - 2500
    - 1800
    - 0
  loss_device: cpu

  evaluation:
    env_seed: 23
    n_envs: 64
    n_processes: 8
